SYSTEM=[Matrix_Rc+1j*w(1)*Matrix_Lcc,...
        -(Matrix_Projm*(Matrix_G_m*Matrix_Nmc)).';... 

        Matrix_Projm*(Matrix_G_m*Matrix_Nmc),...
        Matrix_Rm+(1/(1j*w))*(Matrix_Cb_m.'*Matrix_Pm_ss*Matrix_Cb_m)];
return


    