function [sys] = fun_system_MF(NN,G,radius,np_gauss,Wint,PPgh,ll_h,ut_h,gauss_W,...
                               ne_cap_max,Cap_Elem,...
                               NN_xx1,NN_xx2,PPg_xx,ll_xx,ll_tot_xx,...
                               nSticks,N_vol_sou,N_node_app,R,omega,Aobj,Geapp,A_eapp,R_app,L_app,Cinv_app,A_napp,...
                               ret,beta,...
                               ii,jj)

sys=zeros(length(ii),length(jj));
                           
ii1=intersect(ii,1:nSticks); len_ii1=length(ii1);
ii2=intersect(ii,nSticks+1:nSticks+N_vol_sou); len_ii2=length(ii2);
ii3=intersect(ii,nSticks+N_vol_sou+1:nSticks+N_vol_sou+N_node_app); len_ii3=length(ii3);

 
jj1=intersect(jj,1:nSticks); len_jj1=length(jj1);
jj2=intersect(jj,nSticks+1:nSticks+N_vol_sou); len_jj2=length(jj2);
jj3=intersect(jj,nSticks+N_vol_sou+1:nSticks+N_vol_sou+N_node_app); len_jj3=length(jj3);

%%
if ~isempty(ii1)
    ii1toP=unique([G(1,ii1),G(2,ii1)]);
    if ~isempty(jj1)
        jj1toP=unique([G(1,jj1),G(2,jj1)]);
        if ret==0
            sys(1:len_ii1,1:len_jj1) =  R(ii1,jj1)+...
                                        L_stick_assemble_matlab_vec_MF(NN,G,radius,...
                                             np_gauss,Wint,PPgh,ll_h,ut_h,gauss_W,ii1,jj1)*1j*omega+...
                                        (Aobj(ii1toP,ii1).'*...
                                              P_stick_assemble_matlab_vec_MF(NN,...
                                              G,radius,np_gauss,ne_cap_max,Cap_Elem,...
                                              NN_xx1,NN_xx2,PPg_xx,ll_xx,...
                                              ll_tot_xx,gauss_W,ii1toP,jj1toP)...
                                        *Aobj(jj1toP,jj1))/(1j*omega);
        else
            sys(1:len_ii1,1:len_jj1) =  R(ii1,jj1)+...
                                        (L_stick_assemble_matlab_vec_MF(NN,G,radius,...
                                             np_gauss,Wint,PPgh,ll_h,ut_h,gauss_W,ii1,jj1).*exp(-1j*beta*dist_edge_edge_MF(NN,G,ii1,jj1)))*1j*omega+...
                                        (Aobj(ii1toP,ii1).'*...
                                              (P_stick_assemble_matlab_vec_MF(NN,...
                                              G,radius,np_gauss,ne_cap_max,Cap_Elem,...
                                              NN_xx1,NN_xx2,PPg_xx,ll_xx,...
                                              ll_tot_xx,gauss_W,ii1toP,jj1toP).*exp(-1j*beta*dist_node_node_MF(NN,ii1toP,jj1toP)))...
                                        *Aobj(jj1toP,jj1))/(1j*omega); 
        end
    end
    if ~isempty(jj2)
        jj20=jj2-nSticks;
        jj2toP=setdiff(unique([Geapp(1,jj20),Geapp(2,jj20)]),0);
        if ret ==0
           sys(1:len_ii1,len_jj1+1:len_jj1+len_jj2) = ...
                                        (Aobj(ii1toP,ii1).'*...
                                              (P_stick_assemble_matlab_vec_MF(NN,...
                                              G,radius,np_gauss,ne_cap_max,Cap_Elem,...
                                              NN_xx1,NN_xx2,PPg_xx,ll_xx,...
                                              ll_tot_xx,gauss_W,ii1toP,jj2toP))...
                                        *A_eapp(jj2toP,jj20))/(1j*omega);      
        else
           sys(1:len_ii1,len_jj1+1:len_jj1+len_jj2) = ...
                                        (Aobj(ii1toP,ii1).'*...
                                              (P_stick_assemble_matlab_vec_MF(NN,...
                                              G,radius,np_gauss,ne_cap_max,Cap_Elem,...
                                              NN_xx1,NN_xx2,PPg_xx,ll_xx,...
                                              ll_tot_xx,gauss_W,ii1toP,jj2toP).*exp(-1j*beta*dist_node_node_MF(NN,ii1toP,jj2toP)))...
                                        *A_eapp(jj2toP,jj20))/(1j*omega);               
        end
    end
    if ~isempty(jj3)
    
    end
end
%%   
if ~isempty(ii2)
    ii20=ii2-nSticks;
    ii2toP=setdiff(unique([Geapp(1,ii20),Geapp(2,ii20)]),0);
    if ~isempty(jj1)
       jj1toP=unique([G(1,jj1),G(2,jj1)]);
       if ret == 0
           sys(len_ii1+1:len_ii1+len_ii2,1:len_jj1) =...
                                       A_eapp(ii2toP,ii20).'*...
                                              P_stick_assemble_matlab_vec_MF(NN,...
                                              G,radius,np_gauss,ne_cap_max,Cap_Elem,...
                                              NN_xx1,NN_xx2,PPg_xx,ll_xx,...
                                              ll_tot_xx,gauss_W,ii2toP,jj1toP)...
                                        *Aobj(jj1toP,jj1)/(1j*omega);    
       else
           sys(len_ii1+1:len_ii1+len_ii2,1:len_jj1) =...
                                       A_eapp(ii2toP,ii20).'*...
                                              (P_stick_assemble_matlab_vec_MF(NN,...
                                              G,radius,np_gauss,ne_cap_max,Cap_Elem,...
                                              NN_xx1,NN_xx2,PPg_xx,ll_xx,...
                                              ll_tot_xx,gauss_W,ii2toP,jj1toP).*exp(-1j*beta*dist_node_node_MF(NN,ii2toP,jj1toP)))...
                                        *Aobj(jj1toP,jj1)/(1j*omega);             
       end
    end
    if ~isempty(jj2)
        jj20=jj2-nSticks;
        jj2toP=setdiff(unique([Geapp(1,jj20),Geapp(2,jj20)]),0);
        if ret ==0
            sys(len_ii1+1:len_ii1+len_ii2,len_jj1+1:len_jj1+len_jj2) = ...
                R_app(ii20,jj20)+1j*omega*L_app(ii20,jj20)...
                +(1/(1j*omega))*Cinv_app(ii20,jj20)+...
                (A_eapp(ii2toP,ii20).'*...
                P_stick_assemble_matlab_vec_MF(NN,...
                                              G,radius,np_gauss,ne_cap_max,Cap_Elem,...
                                              NN_xx1,NN_xx2,PPg_xx,ll_xx,...
                                              ll_tot_xx,gauss_W,ii2toP,jj2toP)*...
                A_eapp(jj2toP,jj20))/(1j*omega);
        else
             sys(len_ii1+1:len_ii1+len_ii2,len_jj1+1:len_jj1+len_jj2) = ...
                R_app(ii20,jj20)+1j*omega*L_app(ii20,jj20)...
                +(1/(1j*omega))*Cinv_app(ii20,jj20)+...
                (A_eapp(ii2toP,ii20).'*...
                (P_stick_assemble_matlab_vec_MF(NN,...
                                              G,radius,np_gauss,ne_cap_max,Cap_Elem,...
                                              NN_xx1,NN_xx2,PPg_xx,ll_xx,...
                                              ll_tot_xx,gauss_W,ii2toP,jj2toP).*exp(-1j*beta*dist_node_node_MF(NN,ii2toP,jj2toP)))*...
                A_eapp(jj2toP,jj20))/(1j*omega);           
        end
    end
    if ~isempty(jj3)
       jj30=jj3-nSticks-N_vol_sou;
       sys(len_ii1+1:len_ii1+len_ii2,len_jj1+len_jj2+1:len_jj1+len_jj2+len_jj3) = ...
            A_napp(jj30,ii20).';
    end
end
%%
if ~isempty(ii3)
   ii30=ii3-nSticks-N_vol_sou;
   if ~isempty(jj1)
   end
   if ~isempty(jj2)
       jj20=jj2-nSticks;
       sys(len_ii1+len_ii2+1:len_ii1+len_ii2+len_ii3,len_jj1+1:len_jj1+len_jj2) = ...
             A_napp(ii30,jj20);
   end
   if ~isempty(jj3)
       
   end
end
end

